### ISSUE TITLE
Incidence and prev troubleshooting

### ISSUE THREAD

**Issue by daniellenewby** [oxford-pharmacoepi/EHDENCancerIncidencePrevalence#3]
Hey @edward-burn :)

Not sure if this a server issue or problem with the inc/prev package but can you try running this study using GOLD pretty please? I have run it on the covid subset and usually it runs through with no errors but when i try with the larger databases it always crashes now. I have reduced the number of outcomes to 2 to reduce time but i am still getting errors and i need to see if someone else gets these errors too.  Thank you :D

![image](https://user-images.githubusercontent.com/16097637/218690643-79e16482-e392-4ea7-85c8-6ac33f2f7641.png)

**Comment by edward-burn** [comment]
Hmmm not seen that one before @daniellenewby . Sure I'll give it a try. Can you add a renv, as it might relate to one of the dependencies?

**Comment by daniellenewby** [comment]
Sure will add it now :) thanks!

**Comment by daniellenewby** [comment]
Added the renv now :) @edward-burn

**Comment by edward-burn** [comment]
@daniellenewby strange, for me this runs the code runs successfully without breaking on the server. To confirm, you were getting the error as above even with just two outcomes and running on cdmgold202007? If so, could you rerun as perhaps something changed with the server inbetween our runs.

If you´re still getting the same error and I´m not then I´m not sure what to suggest ..... @catalamarti have you seen an error like this with IncidencePrevalence before?

**Comment by catalamarti** [comment]
I don't remember seeing this before, it would be nice to reproduce and debug it. We can try when you are back to the office @daniellenewby

**Comment by daniellenewby** [comment]
:( ok good to know its just happening for me.. i wonder if running all the other cancers would cause it to break for you? I@edward-burn - i got another error yesterday which i havent seen before either (was on the covid subset but still another error!). I will try rerunning just on the two outcomes with GOLD again and let you know and yes @catalamarti will record what i am doing so we can debug when i get back thank you :)

![image](https://user-images.githubusercontent.com/16097637/218984664-da2d8514-959d-45aa-b97a-6956f7818020.png)

**Comment by edward-burn** [comment]
@daniellenewby how odd, that's another error I've not seen before. I feel that it is likely related to your environment/ dependencies and not the IncidencePrevalence package (although maybe I'm biased!), but then again we're both on the same RStudio version on the same server...... And this is the same code that worked before on the covid subset?

**Comment by daniellenewby** [comment]
Yes the code has worked before on the covid subset and it has worked previously on GOLD and AURUM before the server became really slow :( the error messages are not consistent so sometimes it does it other times it runs through using the covid subset so it's really hard to debug. I am tempted to delete the repo on the server and pull it again from PDE repo to see if that works as i am all out of ideas!

**Comment by daniellenewby** [comment]
this is a server issue not related to study package so closing - thanks for your help :)
